import { Ubuntu } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";

const inter = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

export const metadata: Metadata = {
  title: "David Acevedo - Frontend Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modals,
}: Readonly<{
  children: React.ReactNode;
  modals: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="theme-color" content="#262626"/>
      </head>
      <body className={`${inter.className} bg-alt`}>
        {children}
        {modals}
      </body>
    </html>
  );
}
