import { Ubuntu, Playfair_Display } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import { cn } from "@/utils/cn";

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"],
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: "--playfair-font",
});

export const metadata: Metadata = {
  title: "David Acevedo - Frontend Developer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modals,
}: Readonly<{
  children: React.ReactNode;
  modals: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="theme-color" content="#262626" />
      </head>
      <body className={cn(ubuntu.className, playfair.variable, "bg-alt")}>
        {children}
        {modals}
      </body>
    </html>
  );
}
